name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: game
    
    game: main.o Pokemon.o
      g++ -o game main.o Pokemon.o
    
    main.o: main.cpp Pokemon.hpp
      g++ -c main.cpp
    
    Pokemon.o: Pokemon.cpp Pokemon.hpp
      g++ -c Pokemon.cpp
    
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
